services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-data/:/opt/keycloak/data/import/
